/*
 Ce script permet de creer les tablespaces necessaire pour POST OFFICE...
*/

CREATE TABLESPACE "USER_DATA" 
    LOGGING 
    DATAFILE '/oracle/oradata/post/USER_DATA.dbf' SIZE 100M 
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/

CREATE 
    TEMPORARY TABLESPACE "TEMPORARY_DATA" TEMPFILE '/oracle/
    oradata/post/TEMPORARY_DATA.dbf' SIZE 72M EXTENT MANAGEMENT 
    LOCAL UNIFORM SIZE 1M;
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE "TEMPORARY_DATA"
/
