/*
 Ce script permet de creer les tablespaces necessaire pour MELODIE...
*/

CREATE TABLESPACE "DATAMELO" 
    LOGGING 
    DATAFILE '/oracle/oradata/arpe/DATAMELO.dbf' SIZE 260M EXTENT
    MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/

CREATE TABLESPACE "INDX" 
    LOGGING 
    DATAFILE '/oracle/oradata/arpe/INDX.dbf' SIZE 200M EXTENT 
    MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/

CREATE TABLESPACE "TOOLS" 
    LOGGING 
    DATAFILE '/oracle/oradata/arpe/TOOLARPE.dbf' SIZE 100M EXTENT
    MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO
/
